### ISSUE TITLE
Panic on during high mem contention and concurrent store request for the same metrics

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#112]
After couple of times this is happening:
```
level=debug name=thanos-store ts=2017-12-08T13:36:30.559067909Z caller=bucket.go:1054 msg="preloaded range" block=01C0MSNM5GS6J537VA4K822STW file=0 numOffsets=21 length=5807 duration=4.399890956s
level=debug name=thanos-store ts=2017-12-08T13:36:30.55943186Z caller=bucket.go:400 msg="preload postings" duration=4.889970819s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb6a652]
goroutine 478309 [running]:
github.com/improbable-eng/thanos/pkg/store.(*lazyPostings).Next(0xc469b264c0, 0x1e3df52f)
    <autogenerated>:1 +0x32
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*mergedPostings).Next(0xc4b6652630, 0x2158fed9fd6d1ba0)
    /home/bartek/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:351 +0x208
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*mergedPostings).Next(0xc4b6652690, 0x2158fed9)
    /home/bartek/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:351 +0x208
github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index.(*intersectPostings).Next(0xc4b66526c0, 0x246dfb94a3f)
    /home/bartek/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/tsdb/index/postings.go:302 +0x33
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).blockSeries(0xc420229490, 0x12c37e0, 0xc529da4b00, 0xc4bbe7a7e0, 0xc4dc2c8cc0, 0x2, 0x2, 0x15fee39c7b3, 0x16036576393, 0x0, ...)
    /home/bartek/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:404 +0x619
github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series.func1(0x0, 0x0)
    /home/bartek/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:511 +0xa7
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc4de432360, 0xc4d8a71920, 0xc4274cb130)
    /home/bartek/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
    /home/bartek/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
```

**Comment by Bplotka** [comment]
Cannot repo.
