### ISSUE TITLE
thans-query - panic serving 10.4.1.60:53904: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nmaupu** [improbable-eng/thanos#363]
Hi !

I am currently having an issue after restarting all my stack (prom + thanos sidecar, thanos-query and thanos store).
I observe a panic on thanos query side :
```
2018/05/31 12:51:05 http: panic serving 10.4.1.60:53904: runtime error: invalid memory address or nil pointer dereference
goroutine 9799 [running]:
net/http.(*conn).serve.func1(0xc42016c280)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xd179c0, 0x142cc60)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/improbable-eng/thanos/pkg/query.(*querier).Select(0xc4202105b0, 0x0, 0xc42000c030, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/improbable-eng/thanos/pkg/query/querier.go:166 +0x134
github.com/improbable-eng/thanos/pkg/query/api.(*API).series(0xc420284640, 0xc42025cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/improbable-eng/thanos/pkg/query/api/v1.go:446 +0x8dd
github.com/improbable-eng/thanos/pkg/query/api.(*API).(github.com/improbable-eng/thanos/pkg/query/api.series)-fm(0xc42025cf00, 0xc42000c028, 0xc4201f2900, 0x14, 0xcbf760, 0xc42003cb70, 0xc420aaa858)
	/go/src/github.com/improbable-eng/thanos/pkg/query/api/v1.go:165 +0x34
github.com/improbable-eng/thanos/pkg/query/api.(*API).Register.func1.1(0xf096e0, 0xc42000c028, 0xc42025cf00)
	/go/src/github.com/improbable-eng/thanos/pkg/query/api/v1.go:147 +0x55
net/http.HandlerFunc.ServeHTTP(0xc420281c20, 0xf096e0, 0xc42000c028, 0xc42025cf00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/improbable-eng/thanos/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xf096e0, 0xc42000c028, 0xc42025cf00)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/NYTimes/gziphandler/gzip.go:279 +0x1f3
net/http.HandlerFunc.ServeHTTP(0xc42049da10, 0xf096e0, 0xc42000c028, 0xc42025cf00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/improbable-eng/thanos/pkg/tracing.HTTPMiddleware.func1(0xf096e0, 0xc42000c028, 0xc42025ce00)
	/go/src/github.com/improbable-eng/thanos/pkg/tracing/http.go:37 +0x577
net/http.HandlerFunc.ServeHTTP(0xc4202b8f00, 0xf096e0, 0xc42000c028, 0xc42025ce00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(Handler).ServeHTTP-fm(0xf096e0, 0xc42000c028, 0xc42025ce00)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/client_golang/prometheus/http.go:179 +0x4d
github.com/improbable-eng/thanos/vendor/github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0xf0aba0, 0xc420282380, 0xc42025ce00)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/client_golang/prometheus/http.go:287 +0x26f
github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route.(*Router).handle.func1(0xf0aba0, 0xc420282380, 0xc42025cc00, 0x0, 0x0, 0x0)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route/route.go:50 +0x222
github.com/improbable-eng/thanos/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420277ad0, 0xf0aba0, 0xc420282380, 0xc42025cc00)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6c1
github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(0xc4202c3be0, 0xf0aba0, 0xc420282380, 0xc42025cc00)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route/route.go:88 +0x4c
net/http.(*ServeMux).ServeHTTP(0xc420580150, 0xf0aba0, 0xc420282380, 0xc42025cc00)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42014e000, 0xf0aba0, 0xc420282380, 0xc42025cc00)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42016c280, 0xf0bce0, 0xc42020c5c0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

I did this curl command :
`curl -v "http://thanos-query:9090/api/v1/series?end=1527770827&match%5B%5D=up&start=1527684427"`

Versions I am using :
prometheus 2.2.1

```
thanos --version
thanos, version v0.0.1 (branch: master, revision: 1516d01e7564c901e8f229a57ee40d76b8ceebb1)
  build user:       circleci@28388de946b9
  build date:       20180410-15:01:13
  go version:       go1.10.1
```

**Comment by nmaupu** [comment]
More information, I tried an older build than master docker image and it works.
This version is the following :
```
# thanos --version
thanos, version v0.0.1 (branch: fixing-warnings-empty, revision: 588efa925cd3a472c6510a282240b4fa8c2c3bf3)
  build user:       nmaupu@debian
  build date:       20180504-14:24:18
  go version:       go1.9.2
```

**Comment by Bplotka** [comment]
Ok. Can you try the newest master or just `v0.1.0-rc.1`? 

This is quite unlucky because JUST above the version you are using there is commit with `Do not call querier.Select with nil arg` that fixes exactly this issue. Please, next time ensure you are using release/release candidate branches. (: 

Closing it, feel free to reopen if I am not right.
