### ISSUE TITLE
thanos ruler is panicking when google tracing is enabled.

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#534]
**What happened**
Run thanos rule with google tracing - seems like span is not propagated properly.

**What you expected to happen**
Run smoothly
**How to reproduce it (as minimally and precisely as possible)**:
Run thanos rule with gcp tracing enabled (samples and project flags filled)
**Full logs to relevant components**
Thanos ruler:
```
panic: interface conversion: opentracing.SpanContext is opentracing.noopSpanContext, not basictracer.SpanContext
goroutine 222 [running]:
github.com/improbable-eng/thanos/vendor/github.com/opentracing/basictracer-go.(*tracerImpl).StartSpanWithOptions(0xc420094a80, 0xf5102e, 0x20, 0xc420672120, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/opentracing/basictracer-go/tracer.go:178 +0x424
github.com/improbable-eng/thanos/vendor/github.com/opentracing/basictracer-go.(*tracerImpl).StartSpan(0xc420094a80, 0xf5102e, 0x20, 0xc420a50100, 0x1, 0x1, 0x40e238, 0xe4bf40)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/opentracing/basictracer-go/tracer.go:140 +0xdd
github.com/improbable-eng/thanos/pkg/tracing.(*tracer).StartSpan(0xc4203c43c0, 0xf5102e, 0x20, 0xc420a50100, 0x1, 0x1, 0x0, 0x1)
	/go/src/github.com/improbable-eng/thanos/pkg/tracing/tracing.go:55 +0x79
github.com/improbable-eng/thanos/pkg/tracing.StartSpan(0x1006700, 0xc420ef8000, 0xf5102e, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4210d91f8, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/tracing/tracing.go:45 +0xf0
main.queryPrometheusInstant(0x1006700, 0xc420ef8000, 0xff9960, 0xc4203a02a0, 0xc420cb2c20, 0x12, 0xc42023ccb0, 0x6b, 0x1a36c9ea, 0xed33af98d, ...)
	/go/src/github.com/improbable-eng/thanos/cmd/thanos/rule.go:479 +0x5a1
main.runRule.func3(0x1006700, 0xc420ef8000, 0xc42023ccb0, 0x6b, 0x1a36c9ea, 0xed33af98d, 0x15d9b80, 0x0, 0x0, 0xc420087708, ...)
	/go/src/github.com/improbable-eng/thanos/cmd/thanos/rule.go:184 +0x384
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc42030a000, 0x1006700, 0xc420ef8000, 0x1a36c9ea, 0xed33af98d, 0x15d9b80, 0xc4200d61c0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/alerting.go:177 +0x102
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1006700, 0xc4205243c0, 0x1a36c9ea, 0xed33af98d, 0x15d9b80, 0xc420664120, 0x0, 0x100cf40, 0xc42030a000)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:338 +0x26f
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval(0xc420664120, 0x1006700, 0xc4205243c0, 0x1a36c9ea, 0xed33af98d, 0x15d9b80)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:406 +0xad
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Group).run.func1()
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:206 +0xc0
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Group).run(0xc420664120, 0x1006700, 0xc4205243c0)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:219 +0x285
github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Manager).Update.func1.1(0xc4201a4600, 0xc420664120)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:509 +0x60
created by github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules.(*Manager).Update.func1
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules/manager.go:504 +0x56

```

**Comment by bwplotka** [comment]
This is due to Prometheus adding tracing support that only allows Global tracer. This is sad, but also basicopentracing implentation we are using is not safely handling case of mismatched tracers (the error is not indicating that problem!)

Worth to add PR for it.
