### ISSUE TITLE
Store: slice bound out of range when fetching >24 hr of metrics

### ISSUE THREAD

**Issue by jalev** [improbable-eng/thanos#785]
**Thanos, Prometheus and Golang version used**

thanos, version 0.2.1-master (branch: HEAD, revision: c54ff552b303fecf7a449eddfa19bde17b44db62)
  build user:       root@d6b82f873c64
  build date:       20190129-12:49:36
  go version:       go1.10.4

**What happened**
When trying to get 24 hours of metrics, some of the metrics go missing, followed by the Store crashing with a slice bound out of range panic. Though the logs show that the indexReader is the failure, we are also getting it on bucketChunkReader.

**What you expected to happen**
Not that

**How to reproduce it (as minimally and precisely as possible)**:

- s3 bucket (5.1TB of tsdb data ,1 or 2 comp levels), resolution 0 (we're working on it)
- index-cache-size: 16gb
- chunk-pool-size: 32gb

**Full logs to relevant components**

<details>Logs
<p>

```
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.325959381Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.12.192\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.325974305Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.13.159\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.325986362Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-prometheus-scrape\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.326012169Z caller=bucket.go:647 msg="Blocks source resolutions" blocks=24 mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.14.253\"}" spans="Range: 1548756000000-1548928800000 Resolution: 0"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.326075825Z caller=bucket.go:647 msg="Blocks source resolutions" blocks=24 mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.12.38\"}" spans="Range: 1548756000000-1548928800000 Resolution: 0"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.32612226Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{cluster=\"thanos-cluster.services.main01.eu-central-1.production.k8stw.com\",prometheus=\"kube-monitoring/k8s\",prometheus_replica=\"prometheus-k8s-1\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.326140644Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{cluster=\"thanos-cluster.services.main02.eu-central-1.production.k8stw.com\",prometheus=\"kube-monitoring/k8s\",prometheus_replica=\"prometheus-k8s-1\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.326154287Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.14.131\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.32616535Z caller=bucket.go:621 msg="No block found" mint=1548761400000 maxt=1548934320000 lset="{monitor=\":tony_wat:\",purpose=\"Scrape\",replica=\"prometheus-172.22.12.108\"}"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: level=debug ts=2019-01-31T11:30:21.326187898Z caller=bucket.go:647 msg="Blocks source resolutions" blocks=24 mint=1548761400000 maxt=1548934320000 lset="{cluster=\"thanos-cluster.services.main01.eu-central-1.production.k8stw.com\",prometheus=\"kube-monitoring/k8s\",prometheus_replica=\"prometheus-k8s-0\"}" spans="Range: 1548756000000-1548928800000 Resolution: 0"
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: panic: runtime error: slice bounds out of range
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: goroutine 29937 [running]:
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: github.com/improbable-eng/thanos/pkg/store.(*bucketIndexReader).loadSeries(0xc72ac9f4a0, 0x11cd9a0, 0xc914e52480, 0xc689296e60, 0x1f8, 0x234, 0x86ee9e0, 0x870ef20, 0x0, 0x0)
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]:         /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1393 +0x54f
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: github.com/improbable-eng/thanos/pkg/store.(*bucketIndexReader).PreloadSeries.func2(0x0, 0x432ea8)
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]:         /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1366 +0xa2
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc8a1cb56e0, 0xc9030b69b0, 0xc9213e28d0)
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]:         /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]: created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
Jan 31 11:30:21 ip-172-22-14-77 thanos-store[21856]:         /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
Jan 31 11:30:22 ip-172-22-14-77 systemd[1]: thanos-store.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 31 11:30:22 ip-172-22-14-77 systemd[1]: thanos-store.service: Failed with result 'exit-code'.
Jan 31 11:30:32 ip-172-22-14-77 systemd[1]: thanos-store.service: Service hold-off time over, scheduling restart.
Jan 31 11:30:32 ip-172-22-14-77 systemd[1]: thanos-store.service: Scheduled restart job, restart counter is at 4.
Jan 31 11:30:32 ip-172-22-14-77 systemd[1]: Stopped Thanos Store.
Jan 31 11:30:32 ip-172-22-14-77 systemd[1]: Started Thanos Store.
```

</p>
</details>

**Anything else we need to know**

`get_range` bucket errors. Lots of them.

![screenshot 2019-01-31 at 11 42 18](https://user-images.githubusercontent.com/1196058/52052071-51682500-254d-11e9-8db8-238fac27b000.png)

**Comment by bwplotka** [comment]
From the code it looks like that we loaded less from bucket then we requeted for?

**Comment by bwplotka** [comment]
Yup, if block is malformed then all sorts of stuff can happen.

**Comment by bwplotka** [comment]
Hm what prometheus version you are running? There was an issue with messed up index versioning: https://github.com/prometheus/tsdb/blob/master/index/index.go#L881
 wonder if it's related.

Good finding though!

**Comment by jalev** [comment]
```
prometheus, version 2.6.0 (branch: HEAD, revision: dbd1d58c894775c0788470944b818cc724f550fb)
  build user:       root@bf5760470f13
  build date:       20181217-15:14:46
  go version:       go1.11.3
```

We've been running it for 2-4 weeks now.

**Comment by jalev** [comment]
Anyway; I've found some graphs which produce bad blocks. I'm going to do some more debugging to find out what blocks they are.

**Comment by jalev** [comment]
Anyway; I've found some graphs which produce bad blocks.

I've added:
```golang
fmt.Printf("Partition is out of range. Seq: %d, blockMeta: %s, blockStats: %s, blockDir: %s\n", seq, r.block.meta.ULID, r.block.meta.Stats, r.block.dir)
```

to: https://github.com/improbable-eng/thanos/blob/e3d06e1451ede4210d9f4743370aa7baea855b9b/pkg/store/bucket.go#L1543-L1546


Which produces the following:
```
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 154126179, offsets: 152576599, lowerBound: 4293417716, blockCapacity: 1600000, blockLength: 1034463
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Partition is out of range. Seq: 2, blockMeta: 01D317DTWSJ7JCZM34Q2ZGXJHE, blockStats: {%!s(uint64=1954330330) %!s(uint64=3919128) %!s(uint64=16337745) %!s(u
int64=0) %!s(int64=0)}, blockDir: /opt/thanos-store/01D317DTWSJ7JCZM34Q2ZGXJHE
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 236929641, offsets: 230482378, lowerBound: 4288520033, blockCapacity: 1600000, blockLength: 1029851
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 193246318, offsets: 191699439, lowerBound: 4293420417, blockCapacity: 1600000, blockLength: 1024855
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Partition is out of range. Seq: 2, blockMeta: 01D31E9J4SPJWZKVJYHS9M071M, blockStats: {%!s(uint64=1955735407) %!s(uint64=3925798) %!s(uint64=16360058) %!s(u
int64=0) %!s(int64=0)}, blockDir: /opt/thanos-store/01D31E9J4SPJWZKVJYHS9M071M
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 154892161, offsets: 148447140, lowerBound: 4288522275, blockCapacity: 1600000, blockLength: 1034416
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 95994309, offsets: 89725113, lowerBound: 4288698100, blockCapacity: 1600000, blockLength: 1004753
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 154902463, offsets: 151610433, lowerBound: 4291675266, blockCapacity: 1600000, blockLength: 1032831
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Partition is out of range. Seq: 2, blockMeta: 01D317DTWR5BRFKKW3YH7M778E, blockStats: {%!s(uint64=1954233757) %!s(uint64=3919128) %!s(uint64=16337746) %!s(u
int64=0) %!s(int64=0)}, blockDir: /opt/thanos-store/01D317DTWR5BRFKKW3YH7M778E
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 154892161, offsets: 151599418, lowerBound: 4291674553, blockCapacity: 1600000, blockLength: 1034416
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 95994309, offsets: 92807518, lowerBound: 4291780505, blockCapacity: 1600000, blockLength: 1004753
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 192585397, offsets: 186108523, lowerBound: 4288490422, blockCapacity: 1600000, blockLength: 1028438
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Partition is out of range. Seq: 2, blockMeta: 01D31W10MSP63X9Z7Q9Y53JVVE, blockStats: {%!s(uint64=1954350008) %!s(uint64=3929137) %!s(uint64=16344647) %!s(u
int64=0) %!s(int64=0)}, blockDir: /opt/thanos-store/01D31W10MSP63X9Z7Q9Y53JVVE
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 154892161, offsets: 154321377, lowerBound: 4294396512, blockCapacity: 1600000, blockLength: 1034416
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 95994309, offsets: 95443742, lowerBound: 4294416729, blockCapacity: 1600000, blockLength: 1004753
Feb 06 17:11:55 ip-172-22-12-55 thanos-store[2047]: Compare offsets from one to the other for block. start: 236929641, offsets: 233635406, lowerBound: 4291673061, blockCapacity: 1600000, blockLength: 1029851
```

Which when compared against `thanos bucket inspect`...

```
| 01D317DTWR5BRFKKW3YH7M778E | 06-02-2019 08:00:00 | 06-02-2019 10:00:00 | 2h0m0s   | 38h0m0s    | 3,919,128  | 1,954,233,757   | 16,337,746    | 1          | false       | monitor=:tony_wat:,purpose=Scrape,replica=prometheus-172.22.12.38                                                                                                                                 | 0s         | sidecar   |
| 01D317DTWSJ7JCZM34Q2ZGXJHE | 06-02-2019 08:00:00 | 06-02-2019 10:00:00 | 2h0m0s   | 38h0m0s    | 3,919,128  | 1,954,330,330   | 16,337,745    | 1          | false       | monitor=:tony_wat:,purpose=Scrape,replica=prometheus-172.22.14.253                                                                                                                                | 0s         | sidecar   |
| 01D31E9J4SPJWZKVJYHS9M071M | 06-02-2019 10:00:00 | 06-02-2019 12:00:00 | 2h0m0s   | 38h0m0s    | 3,925,798  | 1,955,735,407   | 16,360,058    | 1          | false       | monitor=:tony_wat:,purpose=Scrape,replica=prometheus-172.22.12.38                                                                                                                                 | 0s         | sidecar   |
| 01D31W10MSP63X9Z7Q9Y53JVVE | 06-02-2019 14:00:00 | 06-02-2019 16:00:00 | 2h0m0s   | 38h0m0s    | 3,929,137  | 1,954,350,008   | 16,344,647    | 1          | false       | monitor=:tony_wat:,purpose=Scrape,replica=prometheus-172.22.14.253                                                                                                                                | 0s         | sidecar   |
```

**Comment by jalev** [comment]
For now I've made a PR with the change that 'handles' this case.

**Comment by bwplotka** [comment]
Fixed by this: https://github.com/improbable-eng/thanos/pull/837 (:
