### ISSUE TITLE
thanos-store azure index out of range

### ISSUE THREAD

**Issue by sepich** [improbable-eng/thanos#967]
**Thanos, Prometheus and Golang version used**

```
      - args:
        - store
        - --data-dir=/data
        - --cluster.disable
        - --log.level=debug
        - '--objstore.config={type: AZURE, config: {container: thanos-store, storage_account:
          <acc>, storage_account_key: <key>}}'
        image: improbable/thanos:v0.3.2
```

**What happened**
After query comes to store, it fails with:
```
level=debug ts=2019-03-23T09:49:25.157986584Z caller=azure.go:156 msg="getting blob" blob=01D6MYK4GJPPQ03B7P4QBZHCBP/index offset=1246916 length=40
level=debug ts=2019-03-23T09:49:25.159914687Z caller=azure.go:213 msg="check if blob exists" blob=01D6MYK4GJPPQ03B7P4QBZHCBP/index
panic: runtime error: index out of range

goroutine 65375 [running]:
github.com/improbable-eng/thanos/pkg/objstore/azure.parseError(0xc4203b8600, 0x178, 0x178, 0x0)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/azure/helpers.go:68 +0x89
github.com/improbable-eng/thanos/pkg/objstore/azure.(*Bucket).IsObjNotFoundErr(0xc4200ce580, 0x11f6800, 0xc4226d3d70, 0x0)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/azure/azure.go:147 +0x56
github.com/improbable-eng/thanos/pkg/objstore/azure.(*Bucket).Exists(0xc4200ce580, 0x1204d60, 0xc4215ef500, 0xc432a0a0f0, 0x28, 0x0, 0x8, 0xf15c60)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/azure/azure.go:220 +0x325
github.com/improbable-eng/thanos/pkg/objstore/azure.(*Bucket).getBlobReader(0xc4200ce580, 0x1204d60, 0xc4215ef500, 0xc432a0a0f0, 0x28, 0x12bb12, 0x5b4d, 0x120efa0, 0xc422d6e340, 0x0, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/azure/azure.go:160 +0x2d2
github.com/improbable-eng/thanos/pkg/objstore/azure.(*Bucket).GetRange(0xc4200ce580, 0x1204d60, 0xc4215ef500, 0xc432a0a0f0, 0x28, 0x12bb12, 0x5b4d, 0xc427eafe60, 0xc428767400, 0xc428767428, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/azure/azure.go:208 +0x77
github.com/improbable-eng/thanos/pkg/objstore.(*metricBucket).GetRange(0xc420380900, 0x1204d60, 0xc4215ef500, 0xc432a0a0f0, 0x28, 0x12bb12, 0x5b4d, 0x0, 0x1111a7f, 0x449c68, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/objstore/objstore.go:252 +0xf6
github.com/improbable-eng/thanos/pkg/store.(*bucketBlock).readChunkRange(0xc4223160b0, 0x1204d60, 0xc4215ef500, 0x0, 0x12bb12, 0x5b4d, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1107 +0x16a
github.com/improbable-eng/thanos/pkg/store.(*bucketChunkReader).loadChunks(0xc425a779e0, 0x1204d60, 0xc4215ef500, 0xc4225b4938, 0x2, 0x2, 0x0, 0x13165f0012bb12, 0x0, 0x0)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1619 +0xc5
github.com/improbable-eng/thanos/pkg/store.(*bucketChunkReader).preload.func3(0xc4284c0fa8, 0x1)
	/go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1605 +0x9f
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc424c27020, 0xc424c26fc0, 0xc421aef620)
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
	/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
```
Running `bucket verify` results:
```
$ thanos bucket verify '--objstore.config={type: AZURE, config: {container: thanos-store, storage_account: <acc>, storage_account_key: <key>}}'
level=info ts=2019-03-23T09:47:11.025448149Z caller=factory.go:39 msg="loading bucket configuration"
level=warn ts=2019-03-23T09:47:11.271641326Z caller=verify.go:49 msg="GLOBAL COMPACTOR SHOULD __NOT__ BE RUNNING ON THE SAME BUCKET" issues=2 repair=false
level=info ts=2019-03-23T09:47:11.271702726Z caller=index_issue.go:29 msg="started verifying issue" with-repair=false issue=index_issue
level=info ts=2019-03-23T09:47:39.001172655Z caller=index_issue.go:130 msg="verified issue" with-repair=false issue=index_issue
level=info ts=2019-03-23T09:47:39.001214255Z caller=overlapped_blocks.go:25 msg="started verifying issue" with-repair=false issue=overlapped_blocks
level=info ts=2019-03-23T09:47:49.686819105Z caller=verify.go:68 msg="verify completed" issues=2 repair=false
level=info ts=2019-03-23T09:47:49.686980205Z caller=main.go:184 msg=exiting
```
If i present the same Azure Blob container as S3 bucket (via minio) to same thanos-store - it works fine. All the data is returned for any queries without segfaults.

**What you expected to happen**
Azure issues should lead to missing data maybe as in S3, but not to segfaults. 

**How to reproduce it (as minimally and precisely as possible)**:
I can provide files if needed, ping @vglafirov.

**Comment by GiedriusS** [comment]
Hello there, sorry that you ran into troubles. @sepich could you try the master version? This exact thing has been very recently fixed (: https://github.com/improbable-eng/thanos/pull/961 there is more information here

**Comment by sepich** [comment]
Oh, wow! That was even more quick fix than i'd expected, thank you ;)
Confirming this issue is gone on `master-2019-03-23-cf6a67a`
